# Generated by Django 2.1.3 on 2019-01-06 14:25

from django.db import migrations
import csv


def populate_words(apps, schema_editor):
    Word = apps.get_model('text_mining', 'Word')
    word_list = []
    with open('text_mining/static/emolex_pt.csv', 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['word'] not in word_list:
                word_list.append(row['word'])
                w = Word(word=row['word'])
                w.save()


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0004_auto_20190106_1225'),
    ]

    operations = [
        migrations.RunPython(populate_words),
    ]
