# Generated by Django 2.1.3 on 2019-01-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0005_auto_20190106_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='presence',
            new_name='words',
        ),
    ]
