# Generated by Django 2.1.3 on 2019-01-06 14:53

from django.db import migrations
import csv


def populate_emotions(apps, schema_editor):
    Emotion = apps.get_model('text_mining', 'Emotion')
    labels = ['positivo', 'negativo', 'alegria', 'tristeza', 'nojo',
              'antecipação', 'medo', 'surpresa', 'confiança', 'raiva']
    for l in labels:
        e = Emotion(emotion=l)
        e.save()


def populate_presence(apps, schema_editor):
    Emotion = apps.get_model('text_mining', 'Emotion')
    Word = apps.get_model('text_mining', 'Word')

    with open('text_mining/static/emolex_pt.csv', 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if int(row['present']) == 1:
                w = Word.objects.get(word=row['word'])
                e = Emotion.objects.get(emotion=row['emotion'])
                e.words.add(w)


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0006_auto_20190106_1253'),
    ]

    operations = [
        migrations.RunPython(populate_emotions),
        migrations.RunPython(populate_presence),
    ]
