# Generated by Django 2.1.3 on 2019-01-07 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0008_auto_20190106_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), default=('desde o momento de sua ascensão ninguém lhe disputou o cetro; foi proclamada a rainha dos\nsalões.',), size=None),
            preserve_default=False,
        ),
    ]
