# Generated by Django 2.1.5 on 2019-01-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0010_remove_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sents',
        ),
    ]
