# Generated by Django 2.1.5 on 2019-01-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0011_remove_book_sents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
