#!/bin/sh

# Set these paths appropriately

BIN="/home/ubuntu/EmotionAnalysis/TreeTagger/bin"
CMD="/home/ubuntu/EmotionAnalysis/TreeTagger/cmd"
LIB="/home/ubuntu/EmotionAnalysis/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/danish-abbreviations
PARFILE=${LIB}/danish.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
