#!/bin/sh

# Set these paths appropriately

BIN="/home/ubuntu/EmotionAnalysis/TreeTagger/bin"
CMD="/home/ubuntu/EmotionAnalysis/TreeTagger/cmd"
LIB="/home/ubuntu/EmotionAnalysis/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
